name = "TicTacToes"
uuid = "3d68f55c-fe7b-4615-b736-f020b52f0eec"
authors = ["Donald Seinen"]
version = "1.0.0-DEV"

[deps]

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
